# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check links stemming from documentation
        run: make -C docs linkcheck 

      - name: Generate documentation in HTML format
        run: make -C docs html 

      - name: Generate documentation in man page format
        run: make -C docs man 

          #- name: Generate documentation in PDF format
          #  run: make -C docs latexpdf 

      - name: Produce downloadable documentation
        uses: actions/upload-artifact@v2
        with:
          name: elastic-blast-documentation
          path: |
            docs/build/html
            docs/build/man
              #docs/build/latex
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
